version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ubuntu
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    networks:
      - app-network
    ports:
      - "8545:8545"
      - "3000:3000"
#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
 
